name: govulncheck
on:
  schedule:
  - cron: 22 2 * * *
jobs:
  govulncheck:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: go-version
      id: go-version
      run: |
        echo go-version="$(awk '/GO_VERSION:/ { print $2 }' .github/workflows/main.yml | tr -d \')" >> ${GITHUB_OUTPUT}
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        go-version: ${{ steps.go-version.outputs.go-version }}
    - name: install
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: run
      run: |
        govulncheck ./...
